In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
churn=pd.read_csv("churn_prediction.csv")

In [3]:
churn.head()

customer_id  vintage  age gender  dependents     occupation    city  \
0            1     3135   66   Male         0.0  self_employed   187.0   
1            2      310   35   Male         0.0  self_employed     NaN   
2            4     2356   31   Male         0.0       salaried   146.0   
3            5      478   90    NaN         NaN  self_employed  1020.0   
4            6     2531   42   Male         2.0  self_employed  1494.0   

   customer_nw_category  branch_code  days_since_last_transaction  ...    \
0                     2          755                        224.0  ...     
1                     2         3214                         60.0  ...     
2                     2           41                          NaN  ...     
3                     2          582                        147.0  ...     
4                     3          388                         58.0  ...     

   previous_month_end_balance  average_monthly_balance_prevQ  \
0                     1458.71                        1458.71   
1                     8704.66                        7799.26   
2                     5815.29                        4910.17   
3                     2291.91                        2084.54   
4                     1401.72                        1643.31   

   average_monthly_balance_prevQ2  current_month_credit  \
0                         1449.07                  0.20   
1                        12419.41                  0.56   
2                         2815.94                  0.61   
3                         1006.54                  0.47   
4                         1871.12                  0.33   

   previous_month_credit  current_month_debit  previous_month_debit  \
0                   0.20                 0.20                  0.20   
1                   0.56              5486.27                100.56   
2                   0.61              6046.73                259.23   
3                   0.47                 0.47               2143.33   
4                 714.61               588.62               1538.06   

   current_month_balance  previous_month_balance  churn  
0                1458.71                 1458.71      0  
1                6496.78                 8787.61      0  
2                5006.28                 5070.14      0  
3                2291.91                 1669.79      1  
4                1157.15                 1677.16      1  

[5 rows x 21 columns]

In [4]:
churn.shape

(28382, 21)

In [5]:
churn.describe()

customer_id       vintage           age    dependents          city  \
count  28382.000000  28382.000000  28382.000000  25919.000000  27579.000000   
mean   15143.508667   2364.336446     48.208336      0.347236    796.109576   
std     8746.454456   1610.124506     17.807163      0.997661    432.872102   
min        1.000000    180.000000      1.000000      0.000000      0.000000   
25%     7557.250000   1121.000000     36.000000      0.000000    409.000000   
50%    15150.500000   2018.000000     46.000000      0.000000    834.000000   
75%    22706.750000   3176.000000     60.000000      0.000000   1096.000000   
max    30301.000000  12899.000000     90.000000     52.000000   1649.000000   

       customer_nw_category   branch_code  days_since_last_transaction  \
count          28382.000000  28382.000000                 25159.000000   
mean               2.225530    925.975019                    69.997814   
std                0.660443    937.799129                    86.341098   
min                1.000000      1.000000                     0.000000   
25%                2.000000    176.000000                    11.000000   
50%                2.000000    572.000000                    30.000000   
75%                3.000000   1440.000000                    95.000000   
max                3.000000   4782.000000                   365.000000   

       current_balance  previous_month_end_balance  \
count     2.838200e+04                2.838200e+04   
mean      7.380552e+03                7.495771e+03   
std       4.259871e+04                4.252935e+04   
min      -5.503960e+03               -3.149570e+03   
25%       1.784470e+03                1.906000e+03   
50%       3.281255e+03                3.379915e+03   
75%       6.635820e+03                6.656535e+03   
max       5.905904e+06                5.740439e+06   

       average_monthly_balance_prevQ  average_monthly_balance_prevQ2  \
count                   2.838200e+04                    2.838200e+04   
mean                    7.496780e+03                    7.124209e+03   
std                     4.172622e+04                    4.457581e+04   
min                     1.428690e+03                   -1.650610e+04   
25%                     2.180945e+03                    1.832507e+03   
50%                     3.542865e+03                    3.359600e+03   
75%                     6.666887e+03                    6.517960e+03   
max                     5.700290e+06                    5.010170e+06   

       current_month_credit  previous_month_credit  current_month_debit  \
count          2.838200e+04           2.838200e+04         2.838200e+04   
mean           3.433252e+03           3.261694e+03         3.658745e+03   
std            7.707145e+04           2.968889e+04         5.198542e+04   
min            1.000000e-02           1.000000e-02         1.000000e-02   
25%            3.100000e-01           3.300000e-01         4.100000e-01   
50%            6.100000e-01           6.300000e-01         9.193000e+01   
75%            7.072725e+02           7.492350e+02         1.360435e+03   
max            1.226985e+07           2.361808e+06         7.637857e+06   

       previous_month_debit  current_month_balance  previous_month_balance  \
count          2.838200e+04           2.838200e+04            2.838200e+04   
mean           3.339761e+03           7.451133e+03            7.495177e+03   
std            2.430111e+04           4.203394e+04            4.243198e+04   
min            1.000000e-02          -3.374180e+03           -5.171920e+03   
25%            4.100000e-01           1.996765e+03            2.074408e+03   
50%            1.099600e+02           3.447995e+03            3.465235e+03   
75%            1.357553e+03           6.667958e+03            6.654693e+03   
max            1.414168e+06           5.778185e+06            5.720144e+06   

              churn  
count  28382.000000  
mean       0.185329  
std        0.388571  
min        0.000000  
25% 

In [6]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28382 entries, 0 to 28381
Data columns (total 21 columns):
customer_id                       28382 non-null int64
vintage                           28382 non-null int64
age                               28382 non-null int64
gender                            27857 non-null object
dependents                        25919 non-null float64
occupation                        28302 non-null object
city                              27579 non-null float64
customer_nw_category              28382 non-null int64
branch_code                       28382 non-null int64
days_since_last_transaction       25159 non-null float64
current_balance                   28382 non-null float64
previous_month_end_balance        28382 non-null float64
average_monthly_balance_prevQ     28382 non-null float64
average_monthly_balance_prevQ2    28382 non-null float64
current_month_credit              28382 non-null float64
previous_month_credit             28382 non-null

In [10]:
churn.tail()

customer_id  vintage  age  gender  dependents     occupation    city  \
28377        30297     1845   10  Female         0.0        student  1020.0   
28378        30298     4919   34  Female         0.0  self_employed  1046.0   
28379        30299      297   47    Male         0.0       salaried  1096.0   
28380        30300     2585   50    Male         3.0  self_employed  1219.0   
28381        30301     2349   18    Male         0.0        student  1232.0   

       customer_nw_category  branch_code  days_since_last_transaction  ...    \
28377                     2         1207                         70.0  ...     
28378                     2          223                         14.0  ...     
28379                     2          588                          0.0  ...     
28380                     3          274                          NaN  ...     
28381                     2          474                         59.0  ...     

       previous_month_end_balance  average_monthly_balance_prevQ  \
28377                     1076.43                        2282.19   
28378                     4069.21                        3668.83   
28379                    61017.55                       53444.81   
28380                     1625.55                        1683.20   
28381                     2821.34                        3213.44   

       average_monthly_balance_prevQ2  current_month_credit  \
28377                         2787.70                  0.30   
28378                         3865.55                  1.71   
28379                        21925.81               4666.84   
28380                         1857.42                  0.20   
28381                         4447.45                  0.11   

       previous_month_credit  current_month_debit  previous_month_debit  \
28377                   0.30                 0.30                  0.30   
28378                   2.29               901.00               1014.07   
28379                3883.06               168.23                 71.80   
28380                   0.20                 0.20                  0.20   
28381                   7.44               714.40               1094.09   

       current_month_balance  previous_month_balance  churn  
28377                1076.43                 1076.43      0  
28378                3738.54                 3690.32      0  
28379               61078.50                57564.24      1  
28380                1625.55                 1625.55      0  
28381                2402.62                 3260.58      1  

[5 rows x 21 columns]

In [108]:
X= churn.iloc[:,0:20].values
y= churn.iloc[:,-1].values

In [109]:
X

array([[1, 3135, 66, ..., 0.2, 1458.71, 1458.71],
       [2, 310, 35, ..., 100.56, 6496.78, 8787.61],
       [4, 2356, 31, ..., 259.23, 5006.28, 5070.14],
       ...,
       [30299, 297, 47, ..., 71.8, 61078.5, 57564.24],
       [30300, 2585, 50, ..., 0.2, 1625.55, 1625.55],
       [30301, 2349, 18, ..., 1094.09, 2402.62, 3260.58]], dtype=object)

In [110]:
from sklearn.preprocessing import Imputer
sim=Imputer(strategy="mean")
sim1=Imputer(strategy="most_frequent")

In [111]:
X[:,[9]]=sim.fit_transform(X[:,[9]])
X[:,[4,6]]=sim1.fit_transform(X[:,[4,6]])

In [112]:
test=pd.DataFrame(X[:,:])

In [48]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28382 entries, 0 to 28381
Data columns (total 21 columns):
0     28382 non-null object
1     28382 non-null object
2     28382 non-null object
3     27857 non-null object
4     28382 non-null object
5     28302 non-null object
6     28382 non-null object
7     28382 non-null object
8     28382 non-null object
9     28382 non-null object
10    28382 non-null object
11    28382 non-null object
12    28382 non-null object
13    28382 non-null object
14    28382 non-null object
15    28382 non-null object
16    28382 non-null object
17    28382 non-null object
18    28382 non-null object
19    28382 non-null object
20    28382 non-null object
dtypes: object(21)
memory usage: 4.5+ MB


In [113]:
churn['churn'].value_counts()

0    23122
1     5260
Name: churn, dtype: int64

In [114]:
test[3]=test[3].fillna('Male')

In [115]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28382 entries, 0 to 28381
Data columns (total 20 columns):
0     28382 non-null object
1     28382 non-null object
2     28382 non-null object
3     28382 non-null object
4     28382 non-null object
5     28302 non-null object
6     28382 non-null object
7     28382 non-null object
8     28382 non-null object
9     28382 non-null object
10    28382 non-null object
11    28382 non-null object
12    28382 non-null object
13    28382 non-null object
14    28382 non-null object
15    28382 non-null object
16    28382 non-null object
17    28382 non-null object
18    28382 non-null object
19    28382 non-null object
dtypes: object(20)
memory usage: 4.3+ MB


In [116]:
X[:,:]=test

In [117]:
test.head()

0     1   2     3  4              5     6  7     8        9        10  \
0  1  3135  66  Male  0  self_employed   187  2   755      224  1458.71   
1  2   310  35  Male  0  self_employed  1020  2  3214       60  5390.37   
2  4  2356  31  Male  0       salaried   146  2    41  69.9978  3913.16   
3  5   478  90  Male  0  self_employed  1020  2   582      147  2291.91   
4  6  2531  42  Male  2  self_employed  1494  3   388       58   927.72   

        11       12       13    14      15       16       17       18       19  
0  1458.71  1458.71  1449.07   0.2     0.2      0.2      0.2  1458.71  1458.71  
1  8704.66  7799.26  12419.4  0.56    0.56  5486.27   100.56  6496.78  8787.61  
2  5815.29  4910.17  2815.94  0.61    0.61  6046.73   259.23  5006.28  5070.14  
3  2291.91  2084.54  1006.54  0.47    0.47     0.47  2143.33  2291.91  1669.79  
4  1401.72  1643.31  1871.12  0.33  714.61   588.62  1538.06  1157.15  1677.16

In [118]:
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()

In [119]:
X[:,3]=lab.fit_transform(X[:,3].astype(str))
X[:,5]=lab.fit_transform(X[:,5].astype(str))

In [120]:
test=pd.DataFrame(X[:,:])
test.head()

0     1   2  3  4  5     6  7     8        9        10       11       12  \
0  1  3135  66  1  0  4   187  2   755      224  1458.71  1458.71  1458.71   
1  2   310  35  1  0  4  1020  2  3214       60  5390.37  8704.66  7799.26   
2  4  2356  31  1  0  3   146  2    41  69.9978  3913.16  5815.29  4910.17   
3  5   478  90  1  0  4  1020  2   582      147  2291.91  2291.91  2084.54   
4  6  2531  42  1  2  4  1494  3   388       58   927.72  1401.72  1643.31   

        13    14      15       16       17       18       19  
0  1449.07   0.2     0.2      0.2      0.2  1458.71  1458.71  
1  12419.4  0.56    0.56  5486.27   100.56  6496.78  8787.61  
2  2815.94  0.61    0.61  6046.73   259.23  5006.28  5070.14  
3  1006.54  0.47    0.47     0.47  2143.33  2291.91  1669.79  
4  1871.12  0.33  714.61   588.62  1538.06  1157.15  1677.16

In [121]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(categorical_features=[3,5])

In [122]:
X=one.fit_transform(X)
X=X.toarray()

In [123]:
test=pd.DataFrame(X[:,:])
test.head()

0    1    2    3    4    5    6    7    8       9    ...          16  \
0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  3135.0   ...     1458.71   
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  2.0   310.0   ...     5390.37   
2  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  4.0  2356.0   ...     3913.16   
3  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  5.0   478.0   ...     2291.91   
4  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  6.0  2531.0   ...      927.72   

        17       18        19    20      21       22       23       24  \
0  1458.71  1458.71   1449.07  0.20    0.20     0.20     0.20  1458.71   
1  8704.66  7799.26  12419.41  0.56    0.56  5486.27   100.56  6496.78   
2  5815.29  4910.17   2815.94  0.61    0.61  6046.73   259.23  5006.28   
3  2291.91  2084.54   1006.54  0.47    0.47     0.47  2143.33  2291.91   
4  1401.72  1643.31   1871.12  0.33  714.61   588.62  1538.06  1157.15   

        25  
0  1458.71  
1  8787.61  
2  5070.14  
3  1669.79  
4  1677.16  

[5 rows x 26 columns]

In [124]:
test=pd.DataFrame(X[:,:])
test.head()

0    1    2    3    4    5    6    7    8       9    ...          16  \
0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  3135.0   ...     1458.71   
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  2.0   310.0   ...     5390.37   
2  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  4.0  2356.0   ...     3913.16   
3  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  5.0   478.0   ...     2291.91   
4  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  6.0  2531.0   ...      927.72   

        17       18        19    20      21       22       23       24  \
0  1458.71  1458.71   1449.07  0.20    0.20     0.20     0.20  1458.71   
1  8704.66  7799.26  12419.41  0.56    0.56  5486.27   100.56  6496.78   
2  5815.29  4910.17   2815.94  0.61    0.61  6046.73   259.23  5006.28   
3  2291.91  2084.54   1006.54  0.47    0.47     0.47  2143.33  2291.91   
4  1401.72  1643.31   1871.12  0.33  714.61   588.62  1538.06  1157.15   

        25  
0  1458.71  
1  8787.61  
2  5070.14  
3  1669.79  
4  1677.16  

[5 rows x 26 columns]

In [125]:
from sklearn.preprocessing import MinMaxScaler
mimax = MinMaxScaler()
X=mimax.fit_transform(X)

In [126]:
test=pd.DataFrame(X[:,:])
test.head()

0    1    2    3    4    5    6    7         8         9     ...     \
0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.000000  0.232330    ...      
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.000033  0.010221    ...      
2  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.000099  0.171083    ...      
3  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.000132  0.023430    ...      
4  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.000165  0.184842    ...      

         16        17        18        19            20            21  \
0  0.001178  0.000802  0.000005  0.003572  1.548512e-08  8.044683e-08   
1  0.001843  0.002064  0.001118  0.005754  4.482534e-08  2.328724e-07   
2  0.001593  0.001561  0.000611  0.003844  4.890037e-08  2.540426e-07   
3  0.001319  0.000947  0.000115  0.003484  3.749028e-08  1.947660e-07   
4  0.001088  0.000792  0.000038  0.003656  2.608020e-08  3.025648e-04   

             22            23        24        25  
0  2.487609e-08  1.343546e-07  0.000836  0.001158  
1  7.182983e-04  7.110188e-05  0.001707  0.002438  
2  7.916775e-04  1.833021e-04  0.001450  0.001789  
3  6.022631e-08  1.515605e-03  0.000980  0.001195  
4  7.706481e-05  1.087601e-03  0.000784  0.001196  

[5 rows x 26 columns]

In [208]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=0)

In [209]:
from sklearn.linear_model import LogisticRegression
log =LogisticRegression()
log.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [210]:
y_pred=log.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [211]:
acc = accuracy_score(y_test, y_pred)
acc

0.8162344983089064

In [212]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

             precision    recall  f1-score   support

          0       0.82      1.00      0.90      5794
          1       0.25      0.00      0.00      1302

avg / total       0.71      0.82      0.73      7096



In [213]:
from sklearn.tree import DecisionTreeClassifier
dtc =DecisionTreeClassifier(max_depth=10, criterion='gini')
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [214]:
y_pred = dtc.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [215]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

             precision    recall  f1-score   support

          0       0.88      0.93      0.91      5794
          1       0.59      0.43      0.50      1302

avg / total       0.83      0.84      0.83      7096



In [216]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
acc

0.8404735062006764

In [217]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10, metric='euclidean')
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [195]:
y_pred = knn.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [196]:
acc = accuracy_score(y_test,y_pred)
acc

0.810456595264938

In [197]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

             precision    recall  f1-score   support

          0       0.81      0.99      0.90      5772
          1       0.22      0.01      0.01      1324

avg / total       0.70      0.81      0.73      7096



In [198]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion='entropy', max_depth =10)
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [199]:
y_pred = rfc.predict(X_test)
y_pred

array([0, 1, 1, ..., 0, 0, 1], dtype=int64)

In [200]:
acc = accuracy_score(y_test, y_pred)
acc

0.8566798196166855

In [201]:
cm =confusion_matrix(y_test, y_pred)
cm

array([[5609,  163],
       [ 854,  470]], dtype=int64)

In [202]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)

             precision    recall  f1-score   support

          0       0.87      0.97      0.92      5772
          1       0.74      0.35      0.48      1324

avg / total       0.84      0.86      0.84      7096

